pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageNameMajor: 'joaoasrosa/ruby-jekyll-awscli:1'
  imageNameMinor: '$(imageNameMajor).0'
  imageNamePatch: '$(imageNameMinor).0'
  imageNameBuild: '$(imageNamePatch).$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build image major and latest'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageNameMajor)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Build image minor'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageNameMinor)'
    includeLatestTag: false

- task: Docker@0
  displayName: 'Build image patch'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageNamePatch)'
    includeLatestTag: false

- task: Docker@0
  displayName: 'Build image build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageNameBuild)'
    includeLatestTag: false

- script: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test && container-structure-test test --image $(imageNameBuild) --config ./command-tests.yaml
  displayName: 'Run container tests'

- script: echo 'Bypassing for now'
  displayName: 'Scan for vulnerabilities in the Docker image'

- script: mkdir -p ./node_modules && ./node_modules/.bin/snyk auth $(snyk-token) && ./node_modules/.bin/snyk monitor $(imageNameBuild) --docker --org=joaoasrosa
  displayName: 'Monitor vulnerabilities in the Docker image'
  condition: succeededOrFailed()

- task: Docker@0
  displayName: 'Push image major and latest'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageNameMajor)'
    includeLatestTag: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: Docker@0
  displayName: 'Push image minor'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageNameMinor)'
    includeLatestTag: false
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: Docker@0
  displayName: 'Push image patch'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageNamePatch)'
    includeLatestTag: false
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: Docker@0
  displayName: 'Push image build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageNameBuild)'
    includeLatestTag: false
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))